### ISSUE TITLE
deploy targets

### ISSUE THREAD

**Issue by levifelling** [applieddataconsultants/cvhta-web#1]
LIVE - http://cvhta.com/
STAGING - http://sandbox3.adceval.com/cvhta/ (this can be moved to wherever you'd like)

Set up jenkins to promote staging on successful build.

**Comment by wavded** [comment]
STAGING is set up, @bthatcher, can we get http://cvhta.com pointed at the node lb cluster?

**Comment by bthatcher** [comment]
pointed the A record for cvhta.com or 173.245.130.198

**Comment by wavded** [comment]
:rocket:

**Comment by wavded** [comment]
targets set up
